apiVersion:  skaffold/v1beta2
kind: Config
build: 
  local:
    push: false
  artifacts:
    - image: yuriygavriluk/data-sceince-image-search-cars
      context: .
      docker:
        dockerfile: Dockerfile
      sync:
        'app.py' : ./app      
deploy:
  kubectl:
    manifests:
      - k8s/data-science-image-app.yaml